version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Serverless-workflow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1psaz5k5uct1j"
s3_prefix = "Serverless-workflow"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
